[tools]
go = "1.22.5"
rust = "1.76"

[tasks.build]
run = 'docker compose build'

[tasks.dup]
run = 'docker compose up'

[tasks.ddown]
run = 'docker compose down'

[tasks.gqlgen]
dir = "backend"
run = "go run -mod=mod github.com/99designs/gqlgen generate"

[tasks.tidy]
dir = "backend"
run = "go mod tidy"

[tasks.tbls]
depends = ["dup"]
run = """
docker run --rm \
  --network $(basename $(pwd))_default \
  -v $PWD:/work \
  -w /work \
  k1low/tbls:v1.79.4 doc \
  --force \
  --er-format mermaid \
  'postgres://accounting:accounting@db:5432/accounting?sslmode=disable'
"""

[tasks.open-all]
run = """
open http://localhost:3000
open http://localhost:8978
open http://localhost:9090
open http://localhost:8989
"""